import Head from 'next/head'
import Image from 'next/image'
import Header from 'components/Header'
import Learn from 'pages/Learn'

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn Trachtenberg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rabbit.png" />
      </Head>
      <main>
        <Learn />
      </main>
    </>
  )
}

